# Generated by Django 3.1.7 on 2021-03-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thimg',
            field=models.ImageField(default='', upload_to='./static/img'),
        ),
    ]
