# Generated by Django 3.1.7 on 2021-03-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False, verbose_name='')),
                ('title', models.CharField(max_length=3000)),
                ('content', models.TextField(verbose_name='')),
                ('author', models.CharField(max_length=50, verbose_name='')),
                ('desc', models.CharField(max_length=70, verbose_name='')),
                ('time_stamp', models.DateTimeField(verbose_name='')),
            ],
        ),
    ]
