# Generated by Django 3.1.7 on 2021-03-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.TextField(max_length=20)),
                ('lname', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
