# Generated by Django 3.1.7 on 2021-03-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
