# Generated by Django 3.1.7 on 2021-03-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210301_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
