# Generated by Django 3.1.7 on 2021-03-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210301_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='connect',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='connect',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
