# Generated by Django 3.1.7 on 2021-03-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210301_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='email',
            field=models.CharField(default='something', max_length=50),
        ),
        migrations.AlterField(
            model_name='connect',
            name='name',
            field=models.CharField(default='something', max_length=30),
        ),
        migrations.AlterField(
            model_name='connect',
            name='phone',
            field=models.CharField(default='something', max_length=50),
        ),
    ]
